name: 'Write Job Report'
description: 'Generates a Job report and saves it to a file'

inputs:
  report-dir:
    description: 'Directory where the report will be saved'
    # required: true
  report-file:
    description: 'File name of the report'
    # required: true
  job-type:
    description: 'The job type report will be generated for'
    required: true

outputs:
  report-content:
    description: 'Content of the generated report'

runs:
  using: 'node20'
  main: 'index.js'
