name: 'Write Job Report'
description: 'Generates a Job report and saves it to a file'

inputs:
  report-path:
    description: 'Path where the report will be saved'
    required: true
    # default: './report.md'

outputs:
  report-content:
    description: 'Content of the generated report'

runs:
  using: 'node20'
  main: 'index.js'
